
╔══════════════════════════════════════════════════════╗
║         SmartAlpha AI — ET Hackathon 2026            ║
║         Track 6: AI for the Indian Investor          ║
╚══════════════════════════════════════════════════════╝


───────────────────────────────────────────────────────

🔍 Running Scenario 1: Bulk Deal Filing Analysis...
  [1/4] DataAgent...
  [2/4] SignalAgent...
  [3/4] ContextAgent...
  [4/4] AlertAgent...

  💾 Output saved: outputs/bulk_deal_20260328_233855.json

───────────────────────────────────────────────────────

📈 Running Scenario 2: Technical Breakout + Conflicting Signals...
  [1/4] DataAgent...
  [2/4] PatternAgent...
  [3/4] ConflictAgent...
  [4/4] RecommendationAgent...

  💾 Output saved: outputs/technical_20260328_233857.json

───────────────────────────────────────────────────────

📊 Running Scenario 3: Portfolio-Aware News Prioritisation...
{'bulk_deal': {'status': 'SUCCESS',
  'company': 'ABC FMCG Ltd',
  'alert': {'classification': 'DISTRESS_SELLING',
   'confidence': 'HIGH',
   'distress_signals': [],
   'routine_signals': [],
   'key_concern': '',
   'data_points_used': []},
  'signal': {'classification': 'DISTRESS_SELLING',
   'confidence': 'HIGH',
   'distress_signals': [],
   'routine_signals': [],
   'key_concern': '',
   'data_points_used': []},
  'context': {'classification': 'DISTRESS_SELLING',
   'confidence': 'HIGH',
   'distress_signals': [],
   'routine_signals': [],
   'key_concern': '',
   'data_points_used': []},
  'audit_trail': {'scenario_id': 'SCENARIO_1_BULK_DEAL',
   'started_at': '2026-03-28T23:38:53.552267',
   'completed_at': '2026-03-28T23:38:55.269286',
   'total_steps': 4,
   'trail': [{'step': 1,
     'agent': 'DataAgent',
     'action': 'fetch_and_validate_filing',
     'input_summary': 'NSE bulk deal filing endpoint',
     'output_summary': 'ABC FMCG Ltd — 4.2% stake sold at 6.0% discount',
     'reasoning': 'Fetched bulk deal filing and earnings history.',
     'timestamp': '2026-03-28T23:38:53.552334',
     'confidence': '',
     'citations': ['https://www.nseindia.com/companies-listing/corporate-filings-bulk-deals']},
    {'step': 2,
     'agent': 'SignalAgent',
     'action': 'classify_bulk_deal',
     'input_summary': 'Stake: 4.2%, Discount: 6.0%',
     'output_summary': 'DISTRESS_SELLING (HIGH)',
     'reasoning': '',
     'timestamp': '2026-03-28T23:38:54.023711',
     'confidence': '',
     'citations': []},
    {'step': 3,
     'agent': 'ContextAgent',
     'action': 'enrich_with_fundamentals',
     'input_summary': 'Classification=DISTRESS_SELLING',
     'output_summary': 'Risk: None',
     'reasoning': '',
     'timestamp': '2026-03-28T23:38:54.927430',
     'confidence': '',
     'citations': []},
    {'step': 4,
     'agent': 'AlertAgent',
     'action': 'generate_retail_alert',
     'input_summary': 'Final aggregation',
     'output_summary': 'Generated',
     'reasoning': '',
     'timestamp': '2026-03-28T23:38:55.269263',
     'confidence': '',
     'citations': []}]}},
 'technical': {'status': 'SUCCESS',
  'scenario': 'Technical Analysis',
  'stock': 'XYZ Tech Ltd',
  'recommendation': {'fallback': True, 'raw_output': ''},
  'pattern': {'fallback': True, 'raw_output': ''},
  'conflict_analysis': {'fallback': True,
   'raw_output': '{\'fallback\': True, \'raw_output\': \'{"bull_case": "The RSI of 78 indicates a strong uptrend, suggesting the stock may continue to rise. However, it is nearing overbought territory, which could lead to a correction.", "bear_case": "The FII of -1.2 indicates a significant outflow of foreign investments,'},
  'audit_trail': {'scenario_id': 'SCENARIO_2_TECHNICAL',
   'started_at': '2026-03-28T23:38:55.270161',
   'completed_at': '2026-03-28T23:38:57.871460',
   'total_steps': 4,
   'trail': [{'step': 1,
     'agent': 'DataAgent',
     'action': 'fetch_technical_indicators',
     'input_summary': 'NSE price/volume feed + FII filing data',
     'output_summary': 'XYZ Tech Ltd — RSI: 78, Breakout: True, FII: -1.2%',
     'reasoning': 'Fetched OHLCV data, RSI, MACD, FII/DII flows from NSE.',
     'timestamp': '2026-03-28T23:38:55.270211',
     'confidence': '',
     'citations': ['NSE Historical Data + Filing as of 2026-03-27']},
    {'step': 2,
     'agent': 'PatternAgent',
     'action': 'detect_pattern',
     'input_summary': 'RSI=78, Breakout=True',
     'output_summary': "{'fallback': True, 'raw_output': ''}",
     'reasoning': 'Pattern detection complete',
     'timestamp': '2026-03-28T23:38:55.839899',
     'confidence': '',
     'citations': []},
    {'step': 3,
     'agent': 'ConflictAgent',
     'action': 'resolve_conflict',
     'input_summary': 'Bull vs Bear signals',
     'output_summary': '{\'fallback\': True, \'raw_output\': \'{\\\'fallback\\\': True, \\\'raw_output\\\': \\\'{"bull_case": "The RSI of 7',
     'reasoning': 'Conflict evaluated',
     'timestamp': '2026-03-28T23:38:56.841198',
     'confidence': '',
     'citations': []},
    {'step': 4,
     'agent': 'RecommendationAgent',
     'action': 'generate_recommendation',
     'input_summary': 'Final decision',
     'output_summary': "{'fallback': True, 'raw_output': ''}",
     'reasoning': 'Recommendation generated',
     'timestamp': '2026-03-28T23:38:57.871442',
     'confidence': '',
     'citations': []}]}},
 'portfolio': {'status': 'ERROR',
  'error': "'str' object has no attribute 'get'",
  'audit_trail': {'scenario_id': 'SCENARIO_3_PORTFOLIO',
   'started_at': '2026-03-28T23:38:57.871991',
   'completed_at': '2026-03-28T23:38:59.783284',
   'total_steps': 3,
   'trail': [{'step': 1,
     'agent': 'DataAgent',
     'action': 'fetch_portfolio_and_events',
     'input_summary': 'User portfolio + market events',
     'output_summary': '8 stocks, 2 events',
     'reasoning': 'Fetched portfolio and events',
     'timestamp': '2026-03-28T23:38:57.872028',
     'confidence': '',
     'citations': ['https://rbi.org.in/monetary-policy-2026-03',
      'https://meity.gov.in/circular-2026-dl-47']},
    {'step': 2,
     'agent': 'ImpactAgent',
     'action': 'calculate_impact',
     'input_summary': 'portfolio + events',
     'output_summary': '{\'fallback\': True, \'raw_output\': \'json\\n{\\n  "user_id": "retail_investor_001",\\n  "total_invested": ',
     'reasoning': 'Impact calculated',
     'timestamp': '2026-03-28T23:38:59.783248',
     'confidence': '',
     'citations': []},
    {'step': 3,
     'agent': 'PipelineRunner',
     'action': 'error',
     'input_summary': 'pipeline',
     'output_summary': "'str' object has no attribute 'get'",
     'reasoning': 'Recovered',
     'timestamp': '2026-03-28T23:38:59.783280',
     'confidence': '',
     'citations': []}]}}}
